// Generated by: supabase gen types typescript --local > src/types/database.types.ts
// Re-run after each migration to keep in sync.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: "admin" | "intern";
          full_name: string;
          email: string;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          role?: "admin" | "intern";
          full_name: string;
          email: string;
          avatar_url?: string | null;
        };
        Update: {
          role?: "admin" | "intern";
          full_name?: string;
          email?: string;
          avatar_url?: string | null;
        };
      };
      interns: {
        Row: {
          id: string;
          profile_id: string;
          school: string;
          program: string;
          supervisor: string;
          required_hours: number;
          start_date: string;
          end_date: string;
          status: "active" | "completed" | "dropped";
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          school: string;
          program: string;
          supervisor: string;
          required_hours?: number;
          start_date: string;
          end_date: string;
          status?: "active" | "completed" | "dropped";
        };
        Update: {
          profile_id?: string;
          school?: string;
          program?: string;
          supervisor?: string;
          required_hours?: number;
          start_date?: string;
          end_date?: string;
          status?: "active" | "completed" | "dropped";
        };
      };
      time_logs: {
        Row: {
          id: string;
          intern_id: string;
          log_date: string;
          clock_in: string;
          clock_out: string;
          hours: number;
          tasks: string;
          status: "pending" | "approved" | "rejected";
          approved_by: string | null;
          approved_at: string | null;
          reject_reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          intern_id: string;
          log_date: string;
          clock_in: string;
          clock_out: string;
          tasks: string;
          status?: "pending" | "approved" | "rejected";
          approved_by?: string | null;
          approved_at?: string | null;
          reject_reason?: string | null;
        };
        Update: {
          log_date?: string;
          clock_in?: string;
          clock_out?: string;
          tasks?: string;
          status?: "pending" | "approved" | "rejected";
          approved_by?: string | null;
          approved_at?: string | null;
          reject_reason?: string | null;
        };
      };
      audit_log: {
        Row: {
          id: string;
          actor_id: string;
          action: string;
          target_table: string;
          target_id: string;
          payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id: string;
          action: string;
          target_table: string;
          target_id: string;
          payload?: Json | null;
        };
        Update: {
          actor_id?: string;
          action?: string;
          target_table?: string;
          target_id?: string;
          payload?: Json | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
    };
    Enums: {
      user_role: "admin" | "intern";
      intern_status: "active" | "completed" | "dropped";
      log_status: "pending" | "approved" | "rejected";
    };
  };
};
